import {
  FaFutbol,
  FaBasketballBall,
  FaSwimmer,
  FaTheaterMasks,
  FaBook,
  FaChalkboardTeacher,
  FaRunning,
  FaMusic,
  FaPaintBrush,
  FaFilm,
  FaMicrophone,
  FaGraduationCap,
  FaChess,
  FaHandHoldingHeart,
  FaUsers,
  FaLaptopCode,
  FaHandshake,
  FaGlobeEurope,
  FaLeaf,
  FaBullhorn,
} from 'react-icons/fa';

export const ICON_OPTIONS = [
  { value: 'FaFutbol', icon: FaFutbol },
  { value: 'FaBasketballBall', icon: FaBasketballBall },
  { value: 'FaSwimmer', icon: FaSwimmer },
  { value: 'FaTheaterMasks', icon: FaTheaterMasks },
  { value: 'FaBook', icon: FaBook },
  { value: 'FaChalkboardTeacher', icon: FaChalkboardTeacher },
  { value: 'FaRunning', icon: FaRunning },
  { value: 'FaMusic', icon: FaMusic },
  { value: 'FaPaintBrush', icon: FaPaintBrush },
  { value: 'FaFilm', icon: FaFilm },
  { value: 'FaMicrophone', icon: FaMicrophone },
  { value: 'FaGraduationCap', icon: FaGraduationCap },
  { value: 'FaChess', icon: FaChess },
  { value: 'FaHandHoldingHeart', icon: FaHandHoldingHeart },
  { value: 'FaUsers', icon: FaUsers },
  { value: 'FaLaptopCode', icon: FaLaptopCode },
  { value: 'FaHandshake', icon: FaHandshake },
  { value: 'FaGlobeEurope', icon: FaGlobeEurope },
  { value: 'FaLeaf', icon: FaLeaf },
  { value: 'FaBullhorn', icon: FaBullhorn },
];
